FROM svizor/zoomcamp-model:3.10.12-slim
# add your stuff here

RUN pip install --upgrade pip

RUN pip install pipenv

RUN pip install flask

RUN pip install gunicorn

RUN pip install pickle-mixin


WORKDIR /app

COPY ["Pipfile","Pipfile.lock","./"]

RUN pipenv install --system --deploy

COPY ["W5Predict-Q6-ws.py","dv.bin","./"]

EXPOSE 9670
 

ENTRYPOINT [ "gunicorn" , "--bind=0.0.0.0:9670", "W5Predict-Q6-ws:app" ]

